x-rl-default: &rl_default
  name: RequestRateLimiter
  args:
    key-resolver: "#{@rateLimitKeyResolver}"
    redis-rate-limiter.replenishRate: 50
    redis-rate-limiter.burstCapacity: 100
    redis-rate-limiter.requestedTokens: 1

server:
  port: 9000
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 2s
  application:
    name: gateway-server
  cloud:
    discovery:
      enabled: true
    gateway:
      server:
        webflux:
          routes:
            - id: gateway-auth-refresh
              uri: forward:/
              predicates:
                - Path=/auth/v1/refresh
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 10
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@rateLimitKeyResolver}"
            - id: gateway-auth-default
              uri: forward:/
              predicates:
                - Path=/auth/v1/**
              filters:
                - *rl_default

            - id: search-service-api
              uri: lb://search-service
              predicates:
                - Path=/api/v1/search/**
              filters:
                - *rl_default

            - id: search-service-public
              uri: lb://search-service
              predicates:
                - Path=/public/v1/search/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@rateLimitKeyResolver}"

            - id: book-service-api
              uri: lb://book-service
              predicates:
                - Path=/api/v1/books/**
              filters:
                - *rl_default

            - id: book-service-public
              uri: lb://book-service
              predicates:
                - Path=/public/v1/books/**
              filters:
                - *rl_default

            - id: user-service-api
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**
              filters:
                - *rl_default

            - id: user-service-public
              uri: lb://user-service
              predicates:
                - Path=/public/v1/users/**
              filters:
                - *rl_default

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "kakao-redirect-uri"
            scope:
              - profile_nickname

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
token:
  access:
    secret: ${ACCESS_TOKEN_SECRET}
    expiration-seconds: ${ACCESS_TOKEN_EXPIRATION_SECONDS}
  refresh:
    secret: ${REFRESH_TOKEN_SECRET}
    expiration-seconds: ${REFRESH_TOKEN_EXPIRATION_SECONDS}

user-service:
  base-url: lb://user-service
  internal-path: /internal/v1/users

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
---
spring:
  config:
    activate:
      on-profile: local
    import: optional:file:.env[.properties]
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "http://localhost:9000/login/oauth2/code/kakao"
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/
app:
  auth:
    login-success-redirect-uri: http://localhost:63342/today-book-front/login/success
cors:
  allowed-origins:
    - http://localhost:63342
---
spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "https://dev-api.todaybook.life/login/oauth2/code/kakao"

app:
  auth:
    login-success-redirect-uri: https://today-book.github.io/today-book-front/login/success

cors:
  allowed-origins:
    - https://today-book.github.io

eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-server:9100/eureka/