name: Deploy to Amazon EC2
on:
  push:
    branches: [ "dev" ]

env:
  APP_NAME: gateway-server
  REGISTRY: ghcr.io
  IMAGE_NAME: today-book/gateway-server-dev
  VERSION: latest
  PROFILE: dev

jobs:
  deploy:
    environment: dev
    name: Build Docker Image and Deploy EC2
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK # JDK 지정
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE_URI=$IMAGE" >> $GITHUB_ENV

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEV_REMOTE_IP }}
          username: ${{ secrets.DEV_REMOTE_USER }}
          key: ${{ secrets.DEV_REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.DEV_REMOTE_SSH_PORT }}
          script: |
            echo "--- 배포 시작 ---"
            sudo docker stop ${{ env.APP_NAME }} || true
            sudo docker rm ${{ env.APP_NAME }} || true
            sudo docker rmi ${{ env.IMAGE_URI }} || true
            
            echo "GHCR 로그인"
            echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            echo "이미지 Pull"
            sudo docker pull ${{ env.IMAGE_URI }}
            
            sudo docker run -d --name ${{ env.APP_NAME }} -p 9000:9000 \
            -e SPRING_PROFILES_ACTIVE=${{ env.PROFILE }} \
            -e USER_SERVICE_URL=${{ secrets.DEV_USER_SERVICE_URL }} \
            -e KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} \
            -e KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }} \
            -e ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} \
            -e REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }} \
            -e ACCESS_TOKEN_EXPIRATION_SECONDS=${{ secrets.ACCESS_TOKEN_EXPIRATION_SECONDS }} \
            -e REFRESH_TOKEN_EXPIRATION_SECONDS=${{ secrets.REFRESH_TOKEN_EXPIRATION_SECONDS }} \
            -e REDIS_HOST=redis \
            -e REDIS_PASSWORD=${{ secrets.DEV_REDIS_PASSWORD }} \
            --network internal-net \
            ${{ env.IMAGE_URI }}
            
            echo "--- 배포 완료 ---"
